### ISSUE TITLE
Removing broken links from lists

### ISSUE THREAD

**Issue by basharovV** [sindresorhus/awesome#1810]
I've got a list of [every dead or broken link in every awesome list](https://github.com/basharovV/StumbleUponAwesome/tree/master/extension/data/broken-urls/awesome), along with the error, which is probably useful to the list maintainers. 

Here is the output from my cleanup script, which checks every URL in every awesome list:
```
Total urls: 47941  Valid urls: 41299 Invalid urls: 6642  HTTP errors: 2044  Other errors: 2406
```

That's 14% of all links being unavailable or gone...

If you own or maintain an awesome list, feel free to find the file for your list and check if it has any dead links.

**Comment by bernardoduarte** [comment]
Here's a tool that could help check if your lists links are alive: https://github.com/dkhamsing/awesome_bot

**Comment by riderx** [comment]
in my repo i use 
```
name: Check Lint

on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
  # Run every first day at 00:00 AM every month.
    - cron: "0 0 * * *"
  pull_request:
    branches: [main]
    paths:
      - 'readme.md'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          retry-after: 10
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown.links.config.json'
      - name: Awesome linter
        run: npx awesome-lint
```
